language: emacs-lisp
env:
  - EVM_EMACS=emacs-25.3-travis
  # FIXME: Emacs > 25.3 does not work at this time.
  # Build at Travis CI produces the following error:
  #
  #   error while loading shared libraries: libgnutls.so.26:
  #   cannot open shared object file: No such file or directory
  #
  # Thus, this is disable for now.  For more see:
  # https://travis-ci.org/jschaf/esup/jobs/641742587
  #
  # - EVM_EMACS=emacs-git-snapshot-travis
before_install:
  - source ./scripts/travis-evm-cask.sh
  - evm install $EVM_EMACS --use --skip
  - emacs --version
  - cask install --verbose
script:
  - cask exec ert-runner
